In [24]:
import pandas as pd

# Load the CSV file into a DataFrame
df = pd.read_csv('C:/Users/ronny somi/Downloads/Cola1.csv', header=None)

# Extract headers and data rows
fiscal_years = df.iloc[1, 1:].tolist()  # Fiscal years (Row 1, skipping first column)
headers = df.iloc[2:22, 0].tolist()  # Row labels (Rows 2-21, Column 0)

# Create the tabular dataset using headers and fiscal years
cleaned_data = pd.DataFrame(df.iloc[2:22, 1:].values, columns=fiscal_years, index=headers)

# Reset index for proper formatting
cleaned_data.reset_index(inplace=True)
cleaned_data.rename(columns={"index": "Metrics"}, inplace=True)

# Save the clean file
cleaned_data.to_csv("cleaned_data.csv", index=False)

df.dropna(inplace=True)  # Drop rows with missing data
df.replace(",", "", regex=True, inplace=True)  # Remove commas from numeric values
df = df.apply(pd.to_numeric, errors='ignore')  # Convert numeric columns

df.to_excel("cleaned_profit_loss.xlsx", index=False)

import pandas as pd

# Manually inputting the dataset based on the provided structure
data = {
    "Metric": [
        "NET OPERATING REVENUES", "Cost of goods sold", "Gross Profit",
        "Selling, general and administrative expenses", "Other operating charges",
        "Operating Income", "Interest income", "Interest expense",
        "Equity income (loss) - net", "Other income (loss) - net",
        "Income before income taxes", "Income taxes", "CONSOLIDATED NET INCOME",
        "Less: Net income attributable to noncontrolling interests",
        "Net income from continuing operations", 
        "Income (Loss) from Discontinued Operations, Net of Tax, Including Portion Attributable to Noncontrolling Interest",
        "NET INCOME ATTRIBUTABLE TO SHAREOWNERS OF THE COCA-COLA COMPANY"
    ],
    "FY '09": [
        30990, 11088, 19902, 11358, 313, 8231, 249, 355, 781, 40,
        8946, 2040, 6906, 82, None, None, 6824
    ],
    "FY '10": [
        35119, 12693, 22426, 13194, 819, 8413, 317, 733, 1025, 5185,
        14207, 2370, 11837, 50, None, None, 11787
    ],
    "FY '11": [
        46542, 18215, 28327, 17422, 732, 10173, 483, 417, 690, 529,
        11458, 2812, 8646, 62, None, None, 8584
    ],
    "FY '12": [
        48017, 19053, 28964, 17738, 447, 10779, 471, 397, 819, 137,
        11809, 2723, 9086, 67, None, None, 9019
    ],
    "FY '13": [
        46854, 18421, 28433, 17310, 895, 10228, 534, 463, 602, 576,
        11477, 2851, 8626, 42, None, None, 8584
    ],
    "FY '14": [
        45998, 17889, 28109, 17218, 1183, 9708, 594, 483, 769, -1263,
        9325, 2201, 7124, 26, None, None, 7098
    ],
    "FY '15": [
        44294, 17482, 26812, 16427, 1657, 8728, 613, 856, 489, 631,
        9605, 2239, 7366, 15, 7366, None, 7351
    ],
    "FY '16": [
        41863, 16465, 25398, 15262, 1510, 8626, 642, 733, 835, -1234,
        8136, 1586, 6550, 23, 6550, None, 6527
    ],
    "FY '17": [
        35410, 13255, 22155, 12654, 1902, 7599, 677, 841, 1071, -1764,
        6742, 5560, 1283, 35, 1182, 101, 1248
    ],
    "FY '18": [
        31856, 11770, 20086, 10307, 1079, 8700, 682, 919, 1008, -1121,
        8350, 1623, 6476, 42, 6727, -251, 6434
    ],
}

# Converting to a DataFrame
df = pd.DataFrame(data)

# Save the cleaned dataset
df.to_csv("cleaned_coca_cola_financials.csv", index=False)

# Print to verify
print(df)

                                               Metric   FY '09   FY '10  \
0                              NET OPERATING REVENUES  30990.0  35119.0
1                                  Cost of goods sold  11088.0  12693.0
2                                        Gross Profit  19902.0  22426.0
3        Selling, general and administrative expenses  11358.0  13194.0
4                             Other operating charges    313.0    819.0
5                                    Operating Income   8231.0   8413.0
6                                     Interest income    249.0    317.0
7                                    Interest expense    355.0    733.0
8                          Equity income (loss) - net    781.0   1025.0
9                           Other income (loss) - net     40.0   5185.0
10                         Income before income taxes   8946.0  14207.0
11                                       Income taxes   2040.0   2370.0
12                            CONSOLIDATED NET INCOME   6906.0  11837.0
13  Less: Net income attributable to noncontrollin...     82.0     50.0
14              Net income from continuing operations      NaN      NaN
15  Income (Loss) from Discontinued Operations, Ne...      NaN      NaN
16  NET INCOME ATTRIBUTABLE TO SHAREOWNERS OF THE ...   6824.0  11787.0

     FY '11   FY '12   FY '13   FY '14   FY '15   FY '16  FY '17  FY '18
0   46542.0  48017.0  46854.0  45998.0  44294.0  41863.0   35410   31856
1   18215.0  19053.0  18421.0  17889.0  17482.0  16465.0   13255   11770
2   28327.0  28964.0  28433.0  28109.0  26812.0  25398.0   22155   20086
3   17422.0  17738.0  17310.0  17218.0  16427.0  15262.0   12654   10307
4     732.0    447.0    895.0   1183.0   1657.0   1510.0    1902    1079
5   10173.0  10779.0  10228.0   9708.0   8728.0   8626.0    7599    8700
6     483.0    471.0    534.0    594.0    613.0    642.0     677     682
7     417.0    397.0    463.0    483.0    856.0    733.0     841     919
8     690.0    819.0    602.0    769.0    489.0    835.0    1071    1008
9     529.0    137.0    576.0  -1263.0    631.0  -1234.0   -1764   -1121
10  11458.0  11809.0  11477.0   9325.0   9605.0   8136.0    6742    8350
11   2812.0   2723.0   2851.0   2201.0   2239.0   1586.0    5560    1623
12   8646.0   9086.0   8626.0   7124.0   7366.0   6550.0    1283    6476
13     62.0     67.0     42.0     26.0     15.0     23.0      35      42
14      NaN      NaN      NaN      NaN   7366.0   6550.0    1182    6727
15      NaN      NaN      NaN      NaN      NaN      NaN     101    -251
16   8584.0   9019.0   8584.0   7098.0   7351.0   6527.0    1248    6434

In [25]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]